<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var $block Template */
?>

<script>
    'use strict';
    (function( blackbird ) {

        blackbird.loadExternalScript = async (url) => {
            return new Promise((resolve, reject) => {
                const scriptWithSameSrc = document.querySelector(`script[src="${url}"]`);
                if (scriptWithSameSrc) {
                    return resolve(scriptWithSameSrc);
                }

                const script = document.createElement('script');
                script.type = 'text/javascript';
                script.async = true;
                script.src = url;

                document.head.appendChild(script);

                script.addEventListener('load', () => {
                    return resolve(script);
                });

                script.addEventListener('error', () => {
                    return reject(new Error(`The url : "${url}", failed to load.`));
                });
            });
        }

        blackbird.loadExternalStyle = async (url) => {
            return new Promise((resolve, reject) => {
                const linkWithSameHref = document.querySelector(`link[href="${url}"]`);
                if (linkWithSameHref) {
                    return resolve(linkWithSameHref);
                }

                const link = document.createElement('link');
                link.type = 'text/css'
                link.rel = 'stylesheet';
                link.href = url;

                document.head.prepend(link);

                link.addEventListener('load', () => {
                    return resolve(link);
                });

                link.addEventListener('error', () => {
                    return reject(new Error(`The url : "${url}", failed to load.`));
                });
            });
        }

        blackbird.loadExternalResource = async (url) => {
            return new Promise((resolve, reject) => {
                const scriptUrlRegex = /\.(js)$/i;
                const styleUrlRegex = /\.(css)$/i;

                if (scriptUrlRegex.test(url)) {
                    return resolve(blackbird.loadExternalScript(url));
                } else if (styleUrlRegex.test(url)) {
                    return resolve(blackbird.loadExternalStyle(url));
                } else {
                    return reject(new Error(`The url : "${url}", is not a valid script/style CDN.`));
                }
            });
        }

    }( window.blackbird = window.blackbird || {} ));
</script>
